export const Creators = {
    'gm': {
        creatorName: 'Journey',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://www.youtube.com/watch?v=1k8craCGpgs?autoplay=1",
        videoHeading: "Journey - Dont stop Believin",
        userId: [],
        creatorLink: "https://twitter.com/JourneyOfficial",
        username: "@JourneyOfficial",
        author: "Journey",
        website: "https://twitter.com/JourneyOfficial",

    },
    'koii': {
        creatorName: 'Eric_3.0',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://www.youtube.com/watch?v=PBJDM_ZY2WI",
        videoHeading: "Deploying a React App with Koii, Arweave and Spheron",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/KoiiEric",
        username: "@KoiiEric",
        author: "Koii-X",
        website: "https://docs.koii.network/build-dapps-with-koii/template-library/deploy",
    },
    'spheron': {
        creatorName: 'Speron',
        editors: {
            preferred: "graphql",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://www.youtube.com/watch?v=Ynfwggyl5rY",
        videoHeading: "Deploying a React App with Koii, Arweave and Spheron",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/prashant_xyz",
        username: "@prashant_xyz",
        author: "Shperon",
        website: "https://spheron.network/",
    },
    'saeta': {
        creatorName: 'Saeta',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/nextExample?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://www.youtube.com/watch?v=y_wZE2G3Ygo&t=4s",
        videoHeading: "Deploying a Next.js App with ARKB",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/saetaeth",
        username: "@saetaeth",
        author: "@saetaeth",
        website: "https://github.com/saeta-eth/arweave-nextjs-example",
    },
    'ArFS': {
        creatorName: 'Lars',
        editors: {
            preferred: "repl",
            repl: "https://replit.com/@Dameon1/Ardrive-ArFS?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://www.youtube.com/watch?v=vFyTXUXUe44&t=56s",
        videoHeading: "Learning to use GraphQL with Arweave and Graph Protocol",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/mclars",
        username: "@mclars",
        author: "Ardrive",
        website: "https://ardrive.io/",
    },
    'nader': {
        creatorName: 'Nader',
        editors: {
            preferred: "arcodeArweave",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://us.glassapi.xyz/1647306621.NfBRvNpXJ38Mc_h42c9Zehmc8i34iVWiNu5Vu1_IC0Q.ac925d47-4a07-4c84-859b-9924f84708b9_uploaded_video_1_1_audio.mp4",
        videoHeading: "Full stack web3 tutorial",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/dabit3",
        username: "@dabit3",
        author: "Edge and Node",
        website: "https://edgeandnode.com/",
    },
    'arweave': {
        creatorName: 'Arweave',
        editors: {
            preferred: "graphql",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            koiiRepl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://arweave.net/9eWS7cfKeNAqPRTrSvMNR-4ub7JEwyOiI4IDXXkUMso",
        videoHeading: "Introduction to Arweave",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/onlyarweave",
        username: "@onlyarweave",
        author: "Arweave.org",
        website: "https://www.arweave.org/",
    },
    'sam': {
        creatorName: 'Sam Williams',
        editors: {
            preferred: "arcode",
            repl: "https://replit.com/@Dameon1/Web3Guide?lite=true",
            arcodeArweave: "https://binrhooxfuw3dh5k6dye45lkm2wn2tqvkhoa4ktkyteyvnvshm.arweave.net/ChsTudctLbGfqvDwTnVqZqzdThVR3A4qasT_JirayO0/#/",
            arcode: "https://arcode.studio/#/",
            koiiRepl: "https://replit.com/@Dameon1/Koii-Funcraiser-repl?lite=true",
            graphql: "https://arweave.net/graphql"
        },
        video: "https://arweave.net/xlraoyFTfk9l4RvaCJ86IYe51xeVEA-gI7KC2hTwh6o",
        videoHeading: "Arweave Build Program",
        notes: "",
        userId: [],
        creatorLink: "https://twitter.com/samecwilliams",
        username: "@samecwilliams",
        author: "Sam Williams",
        website: "https://arwiki.wiki/#/en/creating-a-dapp",
    }
}